---
all:
  children:
    etke_servers:
      children:
        matrix_servers:
          children:
            servers_overrides:
              children:
                zapal_servers:
                  hosts:
                    zapal.team:

                clients_servers:
                  hosts:
                    eco-stream.com.ua:
#
# You can still have hosts here that are NOT in a zapal_servers
# or clients_servers subgroup (just in server_overrides group)
#               hosts:
#                 another-server.com:
